### ISSUE TITLE
Small error about n and p type doping

### ISSUE THREAD

**Issue by tnholzschuh** [PacktPublishing/Modern-Computer-Architecture-and-Organization#1]
The book says n type doping makes the material negatively charged.  This is incorrect.  If silicon is doped with phosphorus (n type doping) then it will have more electrons, but will still be neutrally charged.  Also in a pn junction, the n type material is positively charged, due to electrons flowing to the lower energy region.

For p type doping the reverse is true.

**Comment by jledin** [comment]
Thank you, I agree. The first paragraph on page 32 should not say doping makes a region somewhat negatively or positively charged.
